graph LR
    AppModule --> ConfigModule;
    ConfigModule --> ConfigHostModule;
    ConfigHostModule --> ConfigModule;
    ConfigHostModule --> PrismaModule;
    PrismaModule --> ConfigModule;
    PrismaModule --> ConfigHostModule;
    ConfigModule --> PrismaModule;
    AppModule --> PrismaModule;
    AppModule --> AuthModule;
    AuthModule --> PassportModule;
    PassportModule --> ConfigModule;
    PassportModule --> ConfigHostModule;
    PassportModule --> PrismaModule;
    AuthModule --> JwtModule;
    JwtModule --> ConfigModule;
    JwtModule --> ConfigHostModule;
    JwtModule --> PrismaModule;
    AuthModule --> ConfigModule;
    AuthModule --> ConfigHostModule;
    AuthModule --> PrismaModule;
    AppModule --> UsersModule;
    UsersModule --> ConfigModule;
    UsersModule --> ConfigHostModule;
    UsersModule --> PrismaModule;
    AppModule --> AppsModule;
    AppsModule --> ConfigModule;
    AppsModule --> ConfigHostModule;
    AppsModule --> PrismaModule;
    AppModule --> SubsModule;
    SubsModule --> JwtModule;
    SubsModule --> ConfigModule;
    SubsModule --> ConfigHostModule;
    SubsModule --> PrismaModule;
    AppModule --> SubTokensModule;
    SubTokensModule --> ConfigModule;
    SubTokensModule --> ConfigHostModule;
    SubTokensModule --> PrismaModule;
    AppModule --> ConfigHostModule;
